export const INPUT_CHANGE_HANDLER = 'INPUT_CHANGE_HANDLER';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const SET_INPUT_EMPTY = 'SET_INPUT_EMPTY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const UPDATE_TOTAL_BUDGET = 'UPDATE_TOTAL_BUDGET';
export const INPUT_CHANGE_HANDLER_BUDGET = 'INPUT_CHANGE_HANDLER_BUDGET';